# Site settings
title: Astervoid 2000
email: chuck@chuckbergeron.io
description: "Astervoid 2000 is a hi-action local-multiplayer space brawler. Inspired by the days of classic arcade gaming"

name: astervoid2000
markdown: kramdown
highlighter: rouge

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
gems: [jekyll-assets, uglifier, jekyll-slim, slim]

assets:
  assets:
    - "application.css"
    - "*.woff"
    - "*.woff2"
    - "*.js"
    - "*.mp4"
    - "*.png"
    - "*.jpg"
    - "*.gif"
