# Site settings
title: Astervoid 2000
email: chuck@chuckbergeron.io
description: "A shiny new local multiplayer videogame with that classic 70's feel"

name: astervoid2000
markdown: kramdown
highlighter: rouge

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
gems: [jekyll-assets, uglifier, jekyll-slim, slim]

assets:
  assets:
    - "application.css"
    - "*.woff"
    - "*.woff2"
    - "*.js"
    - "*.mp4"
    - "*.png"
    - "*.jpg"
    - "*.gif"
